@startuml

|#ffede1|读者|
start
    :成功登陆系统;
    repeat
        :选择租借图书;
    	|#D7F9FF|系统|
    	:判断读者是否有租借图书权限;
    repeat while (是否有租借图书权限?)
    |系统|
    if (信用分是否合格？) then (合格)
    	:返回信用分，允许借书;
    else(不合格)
    	:返回不允许借书，并提示提高信用分方法，并中止租借;
    	detach
    endif
    |系统|
    :处理租借请求;
	:查询预约图书订单;
    if (预约订单是否有效？) then (有)
	    :返回所有有效订单;
	    :预约订单列表]
    else(无)
	     :返回无有效预约订单;
	     detach
    endif
         |读者|
         :选择预约订单书目;
         :用户预约数据表]
         |系统|
	    :处理数据;
	    :书目信息表]
         |读者|
         :选择数量、版本和取书日期;
         |系统|
	    :处理数据并安排取书地点;
	    :生成新的借书单]
         |读者|
         :确认借书单并保存;
         |系统|
	    :处理数据并保存借书单;
stop

@enduml