@startuml

|#ffede1|读者|
start
    :成功登陆系统;
    :到指定地点取书;
    if (取书是否成功) then(不成功)
        :返回未到指定地点取书;
        stop
    else(成功)
        |#D7F9FF|系统|
        :产生新的还书单]
    	:提醒还书日期;
    endif
        |读者|
	    :查询还书单信息;
	    if (是否有还书单) then (有)
            if (还书单信息是否正确？) then (正确)
    	        :确认还书单，选择还书操作;
            else(不正确)
    	        :选择反馈问题，并中止还书;
    	        detach
            endif
    	else(无)
            :返回无还书单，用例结束;
            stop
    	endif
    |系统|
    :处理还书操作;
	:查询还书单;
	:所有还书单列表]
    |读者|
    :选择某个还书单;
    :用户某个还书单数据表]
    |系统|
	:处理数据;
	:列出还书地点]
    |读者|
    :到指定地点还书;
    :工作人员或自助机检查书籍完整性;
    if (图书是否完整？) then (否)
    	:确认损坏，并中止还书;
    	:损坏赔偿;
    	detach
    else(是)
    	:确认还书;
    endif
    |系统|
    	:确认还书，并撤销还书单;
stop

@enduml